"""Add index on (user_id, id)

Revision ID: a6fa2ea64e84
Revises: 91bdbf3c5827
Create Date: 2025-09-05 22:07:20.321621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6fa2ea64e84'
down_revision: Union[str, Sequence[str], None] = '91bdbf3c5827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_applications_user_id_id', 'applications', ['user_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_applications_user_id_id', table_name='applications')
    # ### end Alembic commands ###
