"""added interview_date_utc and users.timezone

Revision ID: ad761075c5ed
Revises: f38e62706a65
Create Date: 2025-08-27 16:24:19.755098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad761075c5ed'
down_revision: Union[str, Sequence[str], None] = 'f38e62706a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('interview_date_utc', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('interview_timezone', sa.String(), nullable=True))
    op.drop_column('applications', 'interview_date')
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.add_column('applications', sa.Column('interview_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('applications', 'interview_timezone')
    op.drop_column('applications', 'interview_date_utc')
    # ### end Alembic commands ###
