"""added interview_data and follow_up date

Revision ID: ae3ab4d46e3b
Revises: ad761075c5ed
Create Date: 2025-08-27 17:44:11.346153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3ab4d46e3b'
down_revision: Union[str, Sequence[str], None] = 'ad761075c5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('WAT', 'CAT', 'EAT', 'SAST', 'GMT', 'CET', 'EET', 'MSK', 'UTC', 'AST', 'EST', 'CST', 'MST', 'PST', 'AKST', 'HST', 'IST', 'PKT', 'BST', 'MMT', 'ICT', 'WIB', 'WITA', 'WIT', 'CST_CHINA', 'HKT', 'SGT', 'JST', 'KST', 'AFT', 'IRST', 'GST', 'AST_ARABIA', 'AEST', 'ACST', 'AWST', 'NZST', 'CHAST', 'ART', 'BRT', 'CLT', 'GYT', name='timezone'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'timezone',
               existing_type=sa.Enum('WAT', 'CAT', 'EAT', 'SAST', 'GMT', 'CET', 'EET', 'MSK', 'UTC', 'AST', 'EST', 'CST', 'MST', 'PST', 'AKST', 'HST', 'IST', 'PKT', 'BST', 'MMT', 'ICT', 'WIB', 'WITA', 'WIT', 'CST_CHINA', 'HKT', 'SGT', 'JST', 'KST', 'AFT', 'IRST', 'GST', 'AST_ARABIA', 'AEST', 'ACST', 'AWST', 'NZST', 'CHAST', 'ART', 'BRT', 'CLT', 'GYT', name='timezone'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
