"""added interview_data and follow_up date

Revision ID: f38e62706a65
Revises: b247c9badad7
Create Date: 2025-08-27 08:19:15.524710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38e62706a65'
down_revision: Union[str, Sequence[str], None] = 'b247c9badad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('interview_date', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('follow_up_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'follow_up_date')
    op.drop_column('applications', 'interview_date')
    # ### end Alembic commands ###
